### ISSUE TITLE
Binaries?

### ISSUE THREAD

**Issue by juanriccio** [10x10sw/SuperJX#2]
Hello, would it be possible to have binaries compiled? My music computer runs Windows, but I do not have Visual Studio or any other compiler available. Thank you!

**Comment by 10x10sw** [comment]
Sure, you can download the latest Windows (32-bit) binary here:
https://tenbyten.com/software/superjx/superjxsyxtool.exe.zip

**Comment by 10x10sw** [comment]
Also, macOS:
https://tenbyten.com/software/superjx/superjxsyxtool.macOS.zip

**Comment by juanriccio** [comment]
Great, thanks! If it's not too much to ask, why don't you provide binaries for your other projects - such as dxsyx? Perhaps linking them from README.md, or from some other conspicuous place, could spare you some maintenance such as this issue I opened :-)
THANKS for your great work!
